In [1]:
# Kala Project 1 Notebook

In [2]:
# Dependencies
import pandas as pd
from prophet import Prophet
import datetime as dt
import numpy as np
%matplotlib inline

In [3]:
# Read the avg-household-size data into a DataFrame
df_household_size = pd.read_csv("Resources/avg-household-size.csv",
    index_col='geography')
df_household_size.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, Aleutians East Borough, Alaska to Weston County, Wyoming
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             3220 non-null   int64
 1   statefips         3220 non-null   int64
 2   countyfips        3220 non-null   int64
 3   avghouseholdsize  3220 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 125.8+ KB

In [4]:
# Dislay the df
df_household_size

,index,statefips,countyfips,avghouseholdsize
geography,,,,
"Aleutians East Borough, Alaska",0,2,13,2.43
"Aleutians West Census Area, Alaska",1,2,16,3.59
"Anchorage Municipality, Alaska",2,2,20,2.77
"Bethel Census Area, Alaska",3,2,50,3.86
"Bristol Bay Borough, Alaska",4,2,60,2.50
...,...,...,...,...
"Sweetwater County, Wyoming",3215,56,37,2.64
"Teton County, Wyoming",3216,56,39,2.63
"Uinta County, Wyoming",3217,56,41,2.76
"Washakie County, Wyoming",3218,56,43,2.34
"Weston County, Wyoming",3219,56,45,2.27

In [5]:
# Read the cancer data into a DataFrame
df_cancer = pd.read_csv("Resources/cancer_reg.csv",
    index_col='geography')
df_cancer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Kitsap County, Washington to Geary County, Kansas
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index                    3047 non-null   int64
 1   avganncount              3047 non-null   float64
 2   avgdeathsperyear         3047 non-null   int64
 3   target_deathrate         3047 non-null   float64
 4   incidencerate            3047 non-null   float64
 5   medincome                3047 non-null   int64
 6   popest2015               3047 non-null   int64
 7   povertypercent           3047 non-null   float64
 8   studypercap              3047 non-null   float64
 9   binnedinc                3047 non-null   object
 10  medianage                3047 non-null   float64
 11  medianagemale            3047 non-null   float64
 12  medianagefemale          3047 non-null   float64
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          762 non-null    float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       2895 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  2438 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(4), object(1)
memory usage: 809.4+ KB

In [6]:
df_cancer

,index,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
geography,,,,,,,,,,,,,,,,,,,,,
"Kitsap County, Washington",0,1397.000000,469,164.9,489.800000,61898,260131,11.2,499.748204,"(61494.5, 125635]",...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
"Kittitas County, Washington",1,173.000000,70,161.3,411.600000,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
"Klickitat County, Washington",2,102.000000,50,174.7,349.700000,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
"Lewis County, Washington",3,427.000000,202,194.8,430.400000,44243,75882,17.1,342.637253,"(42724.4, 45201]",...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
"Lincoln County, Washington",4,57.000000,26,144.4,350.100000,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Ellsworth County, Kansas",3042,1962.667684,15,149.6,453.549422,46961,6343,12.4,0.000000,"(45201, 48021.6]",...,54.9,44.6,31.7,13.2,90.280811,3.837754,0.327613,1.700468,51.063830,7.773512
"Finney County, Kansas",3043,1962.667684,43,150.1,453.549422,48609,37118,18.8,377.175494,"(48021.6, 51046.4]",...,53.3,48.6,28.8,17.7,75.706245,2.326771,4.044920,14.130288,52.007937,8.186470
"Ford County, Kansas",3044,1962.667684,46,153.9,453.549422,51144,34536,15.0,1968.959926,"(51046.4, 54545.6]",...,52.6,47.8,26.6,16.8,87.961629,2.313188,1.316472,5.680705,55.153949,7.809192
"Franklin County, Kansas",3045,1962.667684,52,175.0,453.549422,50745,25609,13.3,0.000000,"(48021.6, 51046.4]",...,56.3,49.6,29.5,14.0,92.905681,1.176562,0.244632,2.131790,58.484232,7.582938
"Geary County, Kansas",3046,1962.667684,48,213.6,453.549422,41193,37030,13.9,0.000000,"(40362.7, 42724.4]",...,60.3,22.9,25.1,12.6,70.098132,16.590100,3.177753,1.356457,56.040242,8.981723

In [7]:
df_combined = pd.merge(df_household_size, df_cancer, on="geography", how="outer")
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, Aleutians East Borough, Alaska to Weston County, Wyoming
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index_x                  3220 non-null   int64
 1   statefips                3220 non-null   int64
 2   countyfips               3220 non-null   int64
 3   avghouseholdsize         3220 non-null   float64
 4   index_y                  3047 non-null   float64
 5   avganncount              3047 non-null   float64
 6   avgdeathsperyear         3047 non-null   float64
 7   target_deathrate         3047 non-null   float64
 8   incidencerate            3047 non-null   float64
 9   medincome                3047 non-null   float64
 10  popest2015               3047 non-null   float64
 11  povertypercent           3047 non-null   float64
 12  studypercap              3047 non-null   float64
 13  binnedinc                3047 non-null   object
 14  medianage                3047 non-null   float64
 15  medianagemale            3047 non-null   float64
 16  medianagefemale          3047 non-null   float64
 17  percentmarried           3047 non-null   float64
 18  pctnohs18_24             3047 non-null   float64
 19  pcths18_24               3047 non-null   float64
 20  pctsomecol18_24          762 non-null    float64
 21  pctbachdeg18_24          3047 non-null   float64
 22  pcths25_over             3047 non-null   float64
 23  pctbachdeg25_over        3047 non-null   float64
 24  pctemployed16_over       2895 non-null   float64
 25  pctunemployed16_over     3047 non-null   float64
 26  pctprivatecoverage       3047 non-null   float64
 27  pctprivatecoveragealone  2438 non-null   float64
 28  pctempprivcoverage       3047 non-null   float64
 29  pctpubliccoverage        3047 non-null   float64
 30  pctpubliccoveragealone   3047 non-null   float64
 31  pctwhite                 3047 non-null   float64
 32  pctblack                 3047 non-null   float64
 33  pctasian                 3047 non-null   float64
 34  pctotherrace             3047 non-null   float64
 35  pctmarriedhouseholds     3047 non-null   float64
 36  birthrate                3047 non-null   float64
dtypes: float64(33), int64(3), object(1)
memory usage: 955.9+ KB

In [17]:
display(df_combined)

,index_x,statefips,countyfips,avghouseholdsize,index_y,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
geography,,,,,,,,,,,,,,,,,,,,,
"Aleutians East Borough, Alaska",0,2,13,2.43,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Aleutians West Census Area, Alaska",1,2,16,3.59,2713.0,8.0,3.0,203.3,201.3,68387.0,...,60.4,58.3,11.2,6.2,31.562280,4.732583,37.156932,5.295567,42.882250,4.391052
"Anchorage Municipality, Alaska",2,2,20,2.77,2714.0,1085.0,352.0,167.5,453.3,75200.0,...,NaN,45.9,24.5,12.9,64.944652,5.854427,8.800530,1.747201,48.361303,5.994294
"Bethel Census Area, Alaska",3,2,50,3.86,2715.0,37.0,20.0,218.8,338.2,45808.0,...,25.8,25.1,47.3,36.1,12.016202,0.798830,1.175743,0.343159,45.521390,9.156280
"Bristol Bay Borough, Alaska",4,2,60,2.50,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Sweetwater County, Wyoming",3215,56,37,2.64,1189.0,155.0,49.0,141.1,403.5,72604.0,...,62.7,59.0,21.9,11.3,92.133476,0.866613,0.857679,1.684088,54.385755,8.929776
"Teton County, Wyoming",3216,56,39,2.63,1190.0,83.0,23.0,136.9,402.7,75348.0,...,67.2,46.1,14.4,5.5,93.160325,0.322711,1.900408,2.783380,50.580188,1.745232
"Uinta County, Wyoming",3217,56,41,2.76,1191.0,68.0,24.0,132.8,359.3,56800.0,...,NaN,54.1,24.4,13.0,94.233158,0.195891,0.119446,1.538462,57.451346,6.918372
"Washakie County, Wyoming",3218,56,43,2.34,1192.0,50.0,21.0,182.3,448.0,50802.0,...,49.3,43.8,32.2,13.9,91.238095,0.678571,0.166667,4.142857,51.708428,5.370370
"Weston County, Wyoming",3219,56,45,2.27,1193.0,37.0,17.0,182.6,397.1,55520.0,...,57.6,52.5,29.4,12.4,94.728747,0.209732,0.531320,0.069911,52.344273,17.401046

In [9]:
# Display the percentage of missing values for each column
missing_data = df_combined.isnull().mean() * 100
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)

missing_data

pctsomecol18_24            76.335404
pctprivatecoveragealone    24.285714
pctemployed16_over         10.093168
pctbachdeg18_24             5.372671
pctmarriedhouseholds        5.372671
pctotherrace                5.372671
pctasian                    5.372671
pctblack                    5.372671
pctwhite                    5.372671
pctpubliccoveragealone      5.372671
pctpubliccoverage           5.372671
pctempprivcoverage          5.372671
pctprivatecoverage          5.372671
pctunemployed16_over        5.372671
pctbachdeg25_over           5.372671
pcths25_over                5.372671
index_y                     5.372671
avganncount                 5.372671
pcths18_24                  5.372671
pctnohs18_24                5.372671
percentmarried              5.372671
medianagefemale             5.372671
medianagemale               5.372671
medianage                   5.372671
binnedinc                   5.372671
studypercap                 5.372671
povertypercent              5.372671
popest2015                  5.372671
medincome                   5.372671
incidencerate               5.372671
target_deathrate            5.372671
avgdeathsperyear            5.372671
birthrate                   5.372671
dtype: float64

In [14]:
# Analysis of Mission Data
# pctsomecol18_24 = 76.3% missing data
# pcyprivatecoveragealone = 24.3% missing data
# the other coumns ~ 5.37% missing data

# Do we hadle missing data by removing?
relevant_columns = ['avghouseholdsize', 'incidencerate', 'target_deathrate']
# type(relevant_columns)

df_relevant = df_combined[relevant_columns]
display(df_relevant)

# Drop rows with missing values in the relevant columns
df_relevant_cleaned = df_relevant.dropna()
display(df_relevant_cleaned)

,avghouseholdsize,incidencerate,target_deathrate
geography,,,
"Aleutians East Borough, Alaska",2.43,NaN,NaN
"Aleutians West Census Area, Alaska",3.59,201.3,203.3
"Anchorage Municipality, Alaska",2.77,453.3,167.5
"Bethel Census Area, Alaska",3.86,338.2,218.8
"Bristol Bay Borough, Alaska",2.50,NaN,NaN
...,...,...,...
"Sweetwater County, Wyoming",2.64,403.5,141.1
"Teton County, Wyoming",2.63,402.7,136.9
"Uinta County, Wyoming",2.76,359.3,132.8
"Washakie County, Wyoming",2.34,448.0,182.3
"Weston County, Wyoming",2.27,397.1,182.6

,avghouseholdsize,incidencerate,target_deathrate
geography,,,
"Aleutians West Census Area, Alaska",3.59,201.3,203.3
"Anchorage Municipality, Alaska",2.77,453.3,167.5
"Bethel Census Area, Alaska",3.86,338.2,218.8
"Dillingham Census Area, Alaska",3.56,409.2,216.6
"Fairbanks North Star Borough, Alaska",2.69,424.4,177.2
...,...,...,...
"Sweetwater County, Wyoming",2.64,403.5,141.1
"Teton County, Wyoming",2.63,402.7,136.9
"Uinta County, Wyoming",2.76,359.3,132.8
"Washakie County, Wyoming",2.34,448.0,182.3
"Weston County, Wyoming",2.27,397.1,182.6

In [16]:
# Calculate the correlation matrix
correlation_matrix = df_relevant_cleaned.corr()
display(correlation_matrix)

                  avghouseholdsize  incidencerate  target_deathrate
avghouseholdsize          1.000000      -0.146103         -0.037396
incidencerate            -0.146103       1.000000          0.449432
target_deathrate         -0.037396       0.449432          1.000000

In [25]:
# correlation_pctwhite_pctblack_direct = df_combined['pctwhite'].corr(df_combined['pctblack'])

# Extract the correlations between the specified columns
correlation_pctwhite_pctblack_direct = df_combined['pctwhite'].corr(df_combined['pctblack'])
correlation_pctwhite_pctasian_direct = df_combined['pctwhite'].corr(df_combined['pctasian'])
correlation_pctblack_pctasian_direct = df_combined['pctblack'].corr(df_combined['pctasian'])

print("\nDirect correlation between pctwhite and pctblack:")
print(correlation_pctwhite_pctblack_direct)

print("\nDirect correlation between pctwhite and pctasian:")
print(correlation_pctwhite_pctasian_direct)

print("\nDirect correlation between pctblack and pctasian:")
print(correlation_pctblack_pctasian_direct)

KeyError: 'pctwhite'