In [3]:

#### Import required dependencies
import pandas as pd
from prophet import Prophet
import datetime as dt
import numpy as np
%matplotlib inline

In [11]:

#### Read in the datasets
household_size_data = pd.read_csv("Resources/avg-household-size.csv", index_col='geography')
#household_size_data.info()
household_size_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, Aleutians East Borough, Alaska to Weston County, Wyoming
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             3220 non-null   int64
 1   statefips         3220 non-null   int64
 2   countyfips        3220 non-null   int64
 3   avghouseholdsize  3220 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 125.8+ KB

,index,statefips,countyfips,avghouseholdsize
geography,,,,
"Aleutians East Borough, Alaska",0,2,13,2.43
"Aleutians West Census Area, Alaska",1,2,16,3.59
"Anchorage Municipality, Alaska",2,2,20,2.77
"Bethel Census Area, Alaska",3,2,50,3.86
"Bristol Bay Borough, Alaska",4,2,60,2.50

In [9]:

##
cancer_data = pd.read_csv("Resources/cancer_reg.csv", index_col='geography')
#cancer_data.info()
cancer_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Kitsap County, Washington to Geary County, Kansas
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index                    3047 non-null   int64
 1   avganncount              3047 non-null   float64
 2   avgdeathsperyear         3047 non-null   int64
 3   target_deathrate         3047 non-null   float64
 4   incidencerate            3047 non-null   float64
 5   medincome                3047 non-null   int64
 6   popest2015               3047 non-null   int64
 7   povertypercent           3047 non-null   float64
 8   studypercap              3047 non-null   float64
 9   binnedinc                3047 non-null   object
 10  medianage                3047 non-null   float64
 11  medianagemale            3047 non-null   float64
 12  medianagefemale          3047 non-null   float64
 13  percentmarried           3047 non-null   float64
 14  pctnohs18_24             3047 non-null   float64
 15  pcths18_24               3047 non-null   float64
 16  pctsomecol18_24          762 non-null    float64
 17  pctbachdeg18_24          3047 non-null   float64
 18  pcths25_over             3047 non-null   float64
 19  pctbachdeg25_over        3047 non-null   float64
 20  pctemployed16_over       2895 non-null   float64
 21  pctunemployed16_over     3047 non-null   float64
 22  pctprivatecoverage       3047 non-null   float64
 23  pctprivatecoveragealone  2438 non-null   float64
 24  pctempprivcoverage       3047 non-null   float64
 25  pctpubliccoverage        3047 non-null   float64
 26  pctpubliccoveragealone   3047 non-null   float64
 27  pctwhite                 3047 non-null   float64
 28  pctblack                 3047 non-null   float64
 29  pctasian                 3047 non-null   float64
 30  pctotherrace             3047 non-null   float64
 31  pctmarriedhouseholds     3047 non-null   float64
 32  birthrate                3047 non-null   float64
dtypes: float64(28), int64(4), object(1)
memory usage: 809.4+ KB

,index,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
geography,,,,,,,,,,,,,,,,,,,,,
"Kitsap County, Washington",0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
"Kittitas County, Washington",1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
"Klickitat County, Washington",2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
"Lewis County, Washington",3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
"Lincoln County, Washington",4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

In [15]:

#### Combine the dataframes on geo
combined_data = pd.merge(household_size_data, cancer_data, on="geography", how="outer")
combined_data.info()
combined_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, Aleutians East Borough, Alaska to Weston County, Wyoming
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index_x                  3220 non-null   int64
 1   statefips                3220 non-null   int64
 2   countyfips               3220 non-null   int64
 3   avghouseholdsize         3220 non-null   float64
 4   index_y                  3047 non-null   float64
 5   avganncount              3047 non-null   float64
 6   avgdeathsperyear         3047 non-null   float64
 7   target_deathrate         3047 non-null   float64
 8   incidencerate            3047 non-null   float64
 9   medincome                3047 non-null   float64
 10  popest2015               3047 non-null   float64
 11  povertypercent           3047 non-null   float64
 12  studypercap              3047 non-null   float64
 13  binnedinc                3047 non-null   object
 14  medianage                3047 non-null   float64
 15  medianagemale            3047 non-null   float64
 16  medianagefemale          3047 non-null   float64
 17  percentmarried           3047 non-null   float64
 18  pctnohs18_24             3047 non-null   float64
 19  pcths18_24               3047 non-null   float64
 20  pctsomecol18_24          762 non-null    float64
 21  pctbachdeg18_24          3047 non-null   float64
 22  pcths25_over             3047 non-null   float64
 23  pctbachdeg25_over        3047 non-null   float64
 24  pctemployed16_over       2895 non-null   float64
 25  pctunemployed16_over     3047 non-null   float64
 26  pctprivatecoverage       3047 non-null   float64
 27  pctprivatecoveragealone  2438 non-null   float64
 28  pctempprivcoverage       3047 non-null   float64
 29  pctpubliccoverage        3047 non-null   float64
 30  pctpubliccoveragealone   3047 non-null   float64
 31  pctwhite                 3047 non-null   float64
 32  pctblack                 3047 non-null   float64
 33  pctasian                 3047 non-null   float64
 34  pctotherrace             3047 non-null   float64
 35  pctmarriedhouseholds     3047 non-null   float64
 36  birthrate                3047 non-null   float64
dtypes: float64(33), int64(3), object(1)
memory usage: 955.9+ KB

,index_x,statefips,countyfips,avghouseholdsize,index_y,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
geography,,,,,,,,,,,,,,,,,,,,,
"Aleutians East Borough, Alaska",0,2,13,2.43,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Aleutians West Census Area, Alaska",1,2,16,3.59,2713.0,8.0,3.0,203.3,201.3,68387.0,...,60.4,58.3,11.2,6.2,31.562280,4.732583,37.156932,5.295567,42.882250,4.391052
"Anchorage Municipality, Alaska",2,2,20,2.77,2714.0,1085.0,352.0,167.5,453.3,75200.0,...,NaN,45.9,24.5,12.9,64.944652,5.854427,8.800530,1.747201,48.361303,5.994294
"Bethel Census Area, Alaska",3,2,50,3.86,2715.0,37.0,20.0,218.8,338.2,45808.0,...,25.8,25.1,47.3,36.1,12.016202,0.798830,1.175743,0.343159,45.521390,9.156280
"Bristol Bay Borough, Alaska",4,2,60,2.50,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

#### Drop the NA values
combined_data = combined_data.dropna()